### ISSUE TITLE
gzip - unexpected end of file

### ISSUE THREAD

**Issue by dpetrov** [miyagawa/cpanminus#144]
Sometimes I get the following error:
gzip: stdin: unexpected end of file
/bin/tar: Child returned status 1
/bin/tar: Exiting with failure status due to previous errors
! Failed to unpack Plack-Test-ExternalServer-0.01.tar.gz: no directory
! Failed to fetch distribution Plack-Test-ExternalServer-0.01

I am not quite sure if that's not problem with my installation/OS/gzip actually.  It happens only sometimes and if I run second time cpanm Some::Module the install process completes without errors.

**Comment by giganteous** [comment]
TLDR: I'm unsure if this is a cpanm bug/issue, but it is a noisy error.

I ran into the same issue, let's try to get to the cause of it.

To state the error again:
```
  gzip: stdin: unexpected end of file
  /bin/tar: Child returned status 1
  /bin/tar: Error is not recoverable: exiting now
```

I ran strace on "PERL_CARTON_MIRROR=https://partial.mirror.company.org carton install" that had this behaviour:
```
...
[pid 26097] execve("/usr/bin/perl", ["/usr/bin/perl", "/usr/share/perl5/App/cpanminus/fatscript.pm", "--quiet", "--notest", "-L", "/var/lib/jenkins/workspace/t/local", "--mirror", "https://partial.mirror.company.org", "--mirror", "http://cpan.metacpan.org/", "--mirror", "http://backpan.perl.org/", "--mirror-index", "/var/lib/jenkins/workspace/t/local/cache/modules/02packages.details.txt", "--cascade-search", "--mirror-only", "--save-dists", "/var/lib/jenkins/workspace/t/local/cache", "--with-all-features", "--with-develop", "--cpanfile", "/var/lib/jenkins/workspace/t/cpanfile", "--installdeps", "/var/lib/jenkins/workspace/t/"], [/* 13 vars */]) = 0

...
Process 26102 attached
[pid 26102] execve("/usr/bin/wget", ["/usr/bin/wget", "https://partial.mirror.company.org/authors/id/L/LD/LDS/Crypt-CBC-2.33.tar.gz", "--user-agent", "cpanminus/1.7014 perl/5.020002", "--retry-connrefused", "-q", "-O", "Crypt-CBC-2.33.tar.gz"], [/* 17 vars */]) = 0
[pid 26102] arch_prctl(ARCH_SET_FS, 0x7fd31a5fe780) = 0
[pid 26102] exit_group(8)               = ?
[pid 26097] wait4(26102,  <unfinished ...>
[pid 26102] +++ exited with 8 +++
[pid 26097] <... wait4 resumed> [{WIFEXITED(s) && WEXITSTATUS(s) == 8}], 0, NULL) = 26102
[pid 26097] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=26102, si_uid=999, si_status=8, si_utime=1, si_stime=2} ---
[pid 26097] clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f87cb5179d0) = 26103
Process 26103 attached
[pid 26103] execve("/bin/tar", ["/bin/tar", "ztf", "Crypt-CBC-2.33.tar.gz"], [/* 17 vars */]) = 0
[pid 26103] arch_prctl(ARCH_SET_FS, 0x7f80c7d4e800) = 0
[pid 26103] clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f80c7d4ead0) = 26104
Process 26104 attached
[pid 26104] execve("/var/lib/jenkins/workspace/t/local/bin/gzip", ["gzip", "-d"], [/* 17 vars */]) = -1 ENOENT (No such file or directory)
[pid 26104] execve("/var/lib/jenkins/bin/gzip", ["gzip", "-d"], [/* 17 vars */]) = -1 ENOENT (No such file or directory)
[pid 26104] execve("/usr/local/bin/gzip", ["gzip", "-d"], [/* 17 vars */]) = -1 ENOENT (No such file or directory)
[pid 26104] execve("/usr/bin/gzip", ["gzip", "-d"], [/* 17 vars */]) = -1 ENOENT (No such file or directory)
[pid 26104] execve("/bin/gzip", ["gzip", "-d"], [/* 17 vars */]) = 0
[pid 26104] arch_prctl(ARCH_SET_FS, 0x7fb034f15700) = 0

gzip: stdin: unexpected end of file
```

After the fail, Crypt::CBC gets installed from the next mirror.

As stated earlier, it's not a major issue, but since it's harmless I'd suggest hiding it. E.g. skip the unpack if the file is empty.

I hope this helps, thanks for providing us with this cpanm 👍

**Comment by christopherraa** [comment]
I have run into this issue as well and have tried to test various scenarios. I have narrowed it down to it happening when using `--mirror` with cpanm like so:

    cpanm -n --mirror <URL> --installdeps .

The issue arise when a requirement in the cpanfile does not exist at the mirror (which only hold company-internal packages), since we mean to fetch the "publically available" dependencies directly from CPAN. What is strange is that the cpanm-log will show loglines as follows:

```
==> Found dependencies: Mojolicious
--> Working on Mojolicious
Fetching <URL>/authors/id/S/SR/SRI/Mojolicious-7.61.tar.gz ... OK

gzip: stdin: not in gzip format
/bin/tar: Child returned status 1
/bin/tar: Error is not recoverable: exiting now
! Failed to unpack Mojolicious-7.61.tar.gz: no directory
! Failed to fetch distribution Mojolicious-7.61
! Installing the dependencies failed: Module 'Mojolicious' is not installed
```

While the webserver serving the internal PAN logs as follows:

```
127.0.0.1 - - [19/Jan/2018 12:52:12] code 404, message File not found
127.0.0.1 - - [19/Jan/2018 12:52:12] "GET /authors/id/S/SR/SRI/Mojolicious-7.61.tar.gz HTTP/1.1" 404 - 
```

In the filesystem in the `.cpanm/work/<TIMESTAMP>`-directory a tar.gz-file is created. This varies between bein zero bytes or a couple of bytes depending on if cpanm was run with `--no-lwp`, `--no-wget` or without any such arguments.

Note that cpanm thinks the file was fetched without incident (`OK`) while it clearly was not. Expected behaviour would as I see it be that it would detect that the fetch failed, discard the empty-ish file and try to fetch from CPAN since we did not use the `--mirror-only`-option.

Is this enough to dig further and does this warrant reopening the issue?

**Comment by christopherraa** [comment]
To clarify: curl does not return an error-code when http-requests fail. This is something that has to be acticated explicitly. Hence there is a differende in output depending on what you tell it to do:

```
$ curl --silent $some_failing_url > /dev/null && echo foo
foo
```
VS
```
$ curl --silent --fail $some_failing_url > /dev/null && echo foo
```
