### ISSUE TITLE
new release needed for Parse::PMFile 0.34

### ISSUE THREAD

**Issue by karenetheridge** [miyagawa/cpanminus#424]
Parse::PMFile contains an important fix for parsing `$VERSION` strings that should be bundled into the next cpanm.

Also, is it possible that you also fatpack and use inc::latest? That would help get toolchain fixes into use sooner, and into the hands of people who don't upgrade cpanm frequently.

**Comment by miyagawa** [comment]
> Also, is it possible that you also fatpack and use inc::latest? That would help get toolchain fixes into use sooner, and into the hands of people who don't upgrade cpanm frequently.

a) I don't think inc::latest is intended for runtime (and don't think it works with fatpack anyway) - it's for Makefile.PL/Build.PL to bootstrap from `inc`.

b) No, I would rather use the version that is shipped and embedded in cpanm, rather than accidental buggy upgrade of any of the dependencies breaking cpanm, and being able to install/downgrade anything.

**Comment by karenetheridge** [comment]
> I don't think inc::latest works with fatpacking

good point - we'd need to make some changes to support that.

**Comment by kentfredric** [comment]
You could potentially make a shim system so that:

```
cpanm Foo
```
used "whatevers latest/available"

and for people who are more security/breakage concious you could have it restrain itself with 
```
cpanm --bundled Foo
```

Or similar.

That way when "things get stuck and broken" they can just go "last known good mode that isn't latest while we bootstrap past the breakage"

**Comment by kentfredric** [comment]
You could also potentially toy with the "bundled and installed as pmfiles but not colliding with others" approach.

https://github.com/dbsrgits/dbix-class/compare/ee20ecfc1...3135108#diff-2

Essentially, you stuff a bunch of stuff in 

```
lib/App/cpanminus/_bundle/
``` 
Hide it from the indexer, and then its just a matter of 

Jimmying @INC at the right time to make it visible.

And that should play nicely with inc::latest ( or something like it )

( I assume I understand the relevant toolchain discussion where this emerged as a useful technique )

**Comment by miyagawa** [comment]
I already do a fair amount of those by a) fatpacking them in `fatscript.pm` in lib that are non-indexed on PAUSE and b) inlining all of them in `cpanm` executable. 

Well I'm not interested in learning *how* to do that, the question is *whether* it is required. Given my experience with cpanm broken a couple of times by just bumping fatlib on my end - and granted that's my mistake of shipping it without further careful testing - that'd cause a whole lot more problems if I depend on third party modules being updated on user's systems.

So the answer is No, at least for now.

**Comment by shadowcat-mst** [comment]
This is correct; cpanminus is effectively the anti-toolchain cpan client that hits the 80% solution again and again. Trying to turn it into a production quality client would be foolishness; the idea of cpanm being suitable for production ended when the plugin system was deleted, hence why doy taught miyagawa how to do toolchain work for carton and I didn't, since I'd already been intentionally stabbed in the back.

Once we stop pretending that cpanm is usable in production, and accept that instead it's the best interactive cpan client ever written, the disagreement goes away.

**Comment by ribasushi** [comment]
Given the incomprehensible dogpiling I figured I will add my 2c:

`inc::latest` in essence brings the worst of both worlds: the staleness of bundled pieces combined with the (by now traditional) instability of the basic toolchain building blocks.

> b) No, I would rather use the version that is shipped and embedded in cpanm (and tested on Travis), rather than accidental buggy or incompatible upgrade of any of the dependencies breaking cpanm, making the users stuck in a state where they have to manually roll back these modules.

^^ I Completely agree with the above. If I had tuits I would very much consider taking CPAN.pm down the same line of thought. 

As noted - my 2c
Cheers!

**Comment by shadowcat-mst** [comment]
I wonder if the "real" answer is to have cpanm check for an updated version of itself every so often and complain loudly if it finds one?

**Comment by shadowcat-mst** [comment]
(oh, and if anybody saw my first comment via email before it was edited, yes it was stupid and made no sense; sorry)
