### ISSUE TITLE
Dependency install failures

### ISSUE THREAD

**Issue by mulletboy2** [miyagawa/cpanminus#452]
Ref: commit a411b42390b2bb1c3cd4271eb9dd5767ac0c03ba

cpanfile specifies the following:
requires 'Carp',                                            '== 1.26';
requires 'Exporter',                                        '== 5.65';

Carp 1.26's makefile, PREREQ_PM specifies Exporter => 0
Exporter 5.65's Makefile's PREREQ_PM specifies Carp => '1.05'

Running 'carton install --cached --deployment' (against perl 5.14.4) produces (abbreviated):

Checking if you have Carp == 1.26 ... No (1.20 doesn't satisfy == 1.26)
Unpacking Carp-1.26.tar.gz
Configuring Carp-1.26 ... Checking if your kit is complete...
Looks good
Checking dependencies from MYMETA.json
Checking if you have Exporter == 5.65 ... No (5.64_03 doesn't satisfy == 5.65)
Unpacking Exporter-5.65.tar.gz
Configuring Exporter-5.65 ... Checking if your kit is complete...
Looks good
Checking dependencies from MYMETA.json ...
Checking if you have Carp == 1.26 ... No (1.20 doesn't satisfy == 1.26)
==> Found dependencies: Carp
Already tried Carp. Skipping.
! Installing the dependencies failed: Installed version (1.20) of Carp is not in range '== 1.26'

This manifests itself in the failure to install around 2/3 of our deps.

We can probably get around it without issue by removing the Carp version number, but that doesn't feel like the ideal fix. Should the subdependency installs require versions from the relevant dependency META info, rather than the cpanfile version?

**Comment by miyagawa** [comment]
As you pointed out, that is actually a circular dependencies between Carp and Exporter, and that's a totally different monster to tackle with.

You should rather eliminate that hard dependencies.

**Comment by miyagawa** [comment]
I'll keep this as a known issue, but it's not something as trivial to fix at this moment.

**Comment by miyagawa** [comment]
OK, I looked at this in a bit more details, and now I get what it is doing.

>  Should the subdependency installs require versions from the relevant dependency META info, rather than the cpanfile version?

Well the fix is exactly to look at the version in cpanfile (or more accurately, to *merge* them) so that you don't end up installing an irrelevant version (i.e. latest) as a sub dependencies and gets the requirement ignored.

The unfortunate side effect here is the circular dependencies case for core modules like this, because cpanm just stops when it encounters circular deps.

Maybe it should not merge the root dependencies *only when* it finds the circular dependencies (i.e. Exporter can be built using the core Carp just fine), but that's a little bit of special casing.

**Comment by miyagawa** [comment]
Fixed with 0ea3c71 let's see how the CI proceeds.

**Comment by mulletboy2** [comment]
Excellent, thank you :)

Just for completeness, removing the Carp version number from our cpanfile did sitestep the issue.

**Comment by miyagawa** [comment]
released as 1.7031
