### ISSUE TITLE
Appears to skip running tests for Module-Build

### ISSUE THREAD

**Issue by bingos** [miyagawa/cpanminus#462]
Having built a new shiny v5.22.0 perl, I ran my usual bootstrap script which uses cpanminus.

I noticed that the Module-Build tests weren't run (Module::Build being a configure_requires for Module::Pluggable).

Testing in isolation seemed to confirm this.

https://gist.github.com/bingos/13374695bdf3237728a7

To reproduce, build a copy of v5.22.0 then run:
 
curl -kL http://cpanmin.us | <path to perl> - -v --without-recommends --mirror http://www.cpan.org/ --mirror-only Module::Pluggable

Many thanks.

**Comment by miyagawa** [comment]
Yes, this was an intentional workaround to avoid slow tests giving a "what is this cpanm doing?" experience to the first-time user, while allowing running tests by default for the "regular" distributions.

https://github.com/miyagawa/cpanminus/commit/fd079b22e6bbae7e3ae4a7163f3b10c1cc260178#diff-e31e774722249fc9f77e470201b7431dR2178

Maybe there's an option or an environment variable to tell cpanm to force test everything...

**Comment by bingos** [comment]
Hi,
Thanks for the explanation. I should have checked the commit history, but I was questioning my sanity at the time :)

Some sort of override (whether it be %ENV or a switch) would be appreciated, but I have harnessed the power of sed in the meantime (as you can see from above) to aid me in my nefarious deeds.

Cheers.

**Comment by miyagawa** [comment]
Woah, sed :)

**Comment by bingos** [comment]
Yeah, sed didn't work out so well in practise.

**Comment by kentfredric** [comment]
This fix that targets the "Module::Build" problem causes other things that aren't Module::Build to unreasonably skip tests.

For example, if somebody was to install DBD::SQLite on a fresh copy of perl, `cpanm` would install DBI without running DBI's test suite. ( Because DBD::SQLite configure_reqires DBI ).

Which given how important it is that DBI's test suite pass before people use it, seems like a bad idea.

**Comment by karenetheridge** [comment]
I'd rather us try harder to get Module::Build out of the install path of critical modules. Testing is vital.

**Comment by miyagawa** [comment]
@karenetheridge I'd rather not make this a reason to decide which modules to use when building modules.

**Comment by karenetheridge** [comment]
@miyagawa No, I mean that if installing/testing Module::Build is a big time consideration, let's try to make that better by removing MB from being used by distributions that don't need it (which is already an endeavour that some toolchain people are doing).  We can push MB much farther down the cpan river.

Thanks for the quick release!

**Comment by miyagawa** [comment]
@karenetheridge that's exactly what I fear to hear. If someone on the team maintaining Module::Build tries to keep Module::Build slow with an agenda to remove Module::Build that's a hostile attitude.

Let's try to make that better by making MB tests run faster.

**Comment by karenetheridge** [comment]
> If someone on the team maintaining Module::Build tries to keep Module::Build test slow

This is not what I was suggesting, and no one to my knowledge has this view.

I'm just saying that one of the ways we can make things better is by removing MB from the critical path.

**Comment by miyagawa** [comment]
Sure, Module::Build shouldn't be used for core/dual-life modules unless there's a strong reason to, I agree. Thanks for clarifying.
