### ISSUE TITLE
Installed version (7.04_01) of ExtUtils::MakeMaker is not in range '7.0401'

### ISSUE THREAD

**Issue by kmx** [miyagawa/cpanminus#463]
Hi, I have experienced the following failure with strawberry perl-5.22.0
```
d:\strawberry32>cpanm PSHANGOV/CPAN-Inject-1.14.tar.gz -v
cpanm (App::cpanminus) 1.7034 on perl 5.022000 built for MSWin32-x86-multi-thread-64int
Work directory is D:\STRAWB~2\data/.cpanm/work/1433495963.11684
You have make D:\strawberry32\c\bin\dmake.exe
You have LWP 6.13
Falling back to Archive::Tar 2.04
You have D:\sw\misc\unzip.exe
--> Working on PSHANGOV/CPAN-Inject-1.14.tar.gz
Fetching http://www.cpan.org/authors/id/P/PS/PSHANGOV/CPAN-Inject-1.14.tar.gz ... OK
Unpacking CPAN-Inject-1.14.tar.gz
Entering CPAN-Inject-1.14
Checking configure dependencies from META.yml
Checking if you have ExtUtils::MakeMaker 6.62 ... Yes (7.04_01)
Running Makefile.PL
Configuring CPAN-Inject-1.14 ... Checking if your kit is complete...
Looks good
Generating a dmake-style Makefile
Writing Makefile for CPAN::Inject
Writing MYMETA.yml and MYMETA.json
OK
Checking dependencies from MYMETA.json ...
Checking if you have Test::Script 1.02 ... Yes (1.10)
Checking if you have File::Copy 2.02 ... Yes (2.30)
Checking if you have CPAN 1.36 ... Yes (2.11)
Checking if you have File::Path 1.00 ... Yes (2.09)
Checking if you have Params::Util 0.21 ... Yes (1.07)
Checking if you have CPAN::Checksums 1.05 ... Yes (2.10)
Checking if you have File::Remove 0.38 ... Yes (1.52)
Checking if you have File::chmod 0.30 ... Yes (0.42)
Checking if you have File::Spec 0.80 ... Yes (3.56)
Checking if you have File::Basename 2.6 ... Yes (2.85)
Checking if you have File::stat 1.00 ... Yes (1.07)
Checking if you have Test::More 0.42 ... Yes (1.001014)
Checking if you have ExtUtils::MakeMaker 7.0401 ... No (7.04_01 < 7.0401)
==> Found dependencies: ExtUtils::MakeMaker
Searching ExtUtils::MakeMaker (7.0401) on cpanmetadb ...
Found ExtUtils::MakeMaker 7.04 which doesn't satisfy 7.0401.
! Installing the dependencies failed: Installed version (7.04_01) of ExtUtils::MakeMaker is not in range '7.0401'
! Bailing out the installation for CPAN-Inject-1.14.
```

The interesting thing is that installation via `cpan -i PSHANGOV/CPAN-Inject-1.14.tar.gz` works fine.

-- kmx

**Comment by miyagawa** [comment]
This is a bug in Module::Install bundled in the module in question.
http://weblog.bulknews.net/post/33907905561/do-not-ship-modules-with-module-install-1-04

**Comment by kmx** [comment]
I see, closing the issue

**Comment by miyagawa** [comment]
Like I said above, this is caused by a bug in Module::Install creating a bogus runtime requirement out of the module version you have. 

But also this is then later triggered by the version.pm's weird behavior in version comparison between the alpha vs non-alpha versions, by CPAN::Meta::Requirements which is used by CPAN::Meta::Check.

```
> version->parse("7.04_01") >= version->parse("7.0401")
''

> version->parse("7.0401") >= version->parse("7.0401")
1

> version->parse("7.04_02") >= version->parse("7.0401")
1
```

@rjbs @Leont

**Comment by miyagawa** [comment]
Also, this only happens when perl ships with a newer version of core module with CPAN as an upstream, not just MakeMaker.

I whined about this a while ago on http://weblog.bulknews.net/post/33905644998/makemaker-dev-releases-perl-5-16-and-carton and ran the script again today, against 5.22.0 and am happy to report that this only applies to ExtUtils::MakeMaker today.

so, @bingos do you have an ETA to ship the newer MakeMaker to CPAN that could not only work around the issue but also fix the issue with Carton etc. for repeatable deployment?

**Comment by miyagawa** [comment]
I added a workaround for this in cpanm 1.7035

**Comment by kmx** [comment]
> I added a workaround for this in cpanm 1.7035

nice, thanks
