### ISSUE TITLE
--local-lib installs into wrong directory

### ISSUE THREAD

**Issue by martinthurn-LFT** [miyagawa/cpanminus#479]
My perl -V contains /usr/local/share/perl5
So I say cpanm --local-lib /usr/local/share/perl5 ...
BUT the modules get installed into /usr/local/share/perl5/lib/perl5 !?!
There's no way to get cpanm to install to where perl is actually looking.  cpanm should NOT add "lib/perl5" onto the path I tell it.  I'M SUPPLYING THE EXACT PATH I WANT, PLEASE DO NOT MUCK IT.  
This is perl, v5.10.1 (*) built for x86_64-linux-thread-multi
on CentOS 6.7

**Comment by miyagawa** [comment]
As documented, `--local-lib` option uses [local::lib](https://metacpan.org/release/local-lib) to configure installation path. It is local::lib that adds `lib/perl5` and there's no way you can change this.

To be even more accurate, it is an installer tool (MakeMaker and Module::Build) who decides where to install modules to, and cpanm just sets a flag via local::lib for these tools by setting [INSTALL_BASE](https://metacpan.org/pod/ExtUtils::MakeMaker#INSTALL_BASE) or `--install_base` (for Module::Build).

It is strongly NOT recommended to install into a shared directory lie above, because it will conflict with other package managers. It is better to either a) leave it as perl's configured default site_perl directory or b) to your own local::lib directory such as `~/perl5`.

However, you *can* set the following and cpanm will just honor that, *if you know what you're doing and understand the consequence*:

```
export PERL_MM_OPT="LIB=/usr/local/share/perl5"
export PERL_MB_OPT="--install_path lib=/usr/local/share/perl5 -install_path arch=/usr/local/share/perl5/x86_64-linux"
```

Read perldoc ExtUtils::MakeMaker and Module::Build.
