### ISSUE TITLE
carton fatpack misses lazy-loaded modules

### ISSUE THREAD

**Issue by Grinnz** [miyagawa/cpanminus#571]
The executable produced by carton fatpack using the new Menlo backend is missing some required modules because of lazy loading in Menlo::CLI::Compat. Only module I know for sure is missed is HTTP::Tinyish, but scanning the source, it also looks like at least these should be packed for what Carton needs: Capture::Tiny, local::lib, CPAN::Meta::YAML.

**Comment by mschout** [comment]
I learned today that one reason Menlo::CLI::Compat fails to load is because it needs ```version::vpp```, but only if its running under App::FatPacker::Trace (if you look at the source, you will see this).  But this distribution does not declare a dependency on version.  If version::vpp isn't installed, then this module gets excluded from the fatpack.
