### ISSUE TITLE
About the installation of the latest git master version of cpanminus using the local repo.

### ISSUE THREAD

**Issue by hongyi-zhao** [miyagawa/cpanminus#622]
On Ubuntu 20.10, I tried the following steps to  install the latest git master version of cpanminus:

```
git clone https://github.com/miyagawa/cpanminus.git miyagawa/cpanminus.git
cd miyagawa/cpanminus.git/

cd App-cpanminus/
cpan .

cd ../Menlo
cpan .

cd ../Menlo-Legacy/
cpan .
```
Though the compilation and installation completed successfully, but I still can't figure out whether the above steps are correct. Especially, what's the differences between Menlo-Legacy and Menlo and which one should I use.

Any hints will be highly appreciated. 

Regards,
HY

**Comment by miyagawa** [comment]
in general you're not recommended to install the master version, but it is available as `cpanm` in the root of App-cpanminus and you can cp the file to wherever you want.

**Comment by hongyi-zhao** [comment]
Do you mean there is no need to install Menlo and Menlo-Legacy at all? If so, why still the repo includes them?

**Comment by miyagawa** [comment]
the `cpanm` file is automatically generated including the code from Menlo-Legacy.

**Comment by miyagawa** [comment]
> Especially, what's the differences between Menlo-Legacy and Menlo and which one should I use.

These libraries are meant to be used by cpanm itself, as well as other tools such as cpm, and not meant to be used by end users directly.

**Comment by hongyi-zhao** [comment]
> in general you're not recommended to install the master version, but it is available as `cpanm` in the root of App-cpanminus and you can cp the file to wherever you want.

Do you mean I should prefer `cp ` over instead of `cpan . `?

**Comment by miyagawa** [comment]
I don't think `cpan .` does what you think it does, but that's not the tool I use for installing from a git checkout anyway.

**Comment by hongyi-zhao** [comment]
> I don't think `cpan .` does what you think it does, but that's not the tool I use for installing from a git checkout anyway. 

Then, what's the suggested tool for this case?

> App-cpanminus repository has all sorts of scripts to auto-generate files before shipping to CPAN for a reason, and that's why I do not recommend to install from there.

Where? The git repo or cpan repo?

**Comment by miyagawa** [comment]
> Then, what's the suggested tool for this case?

Like I've said, i do not recommend to install from git at all.

> Where? The git repo or cpan repo?

I do not recommend installing from git repo and i recommend to install it from CPAN.

**Comment by hongyi-zhao** [comment]
> I don't think `cpan .` does what you think it does, but that's not the tool I use for installing from a git checkout anyway. 

See [here](https://www.perlmonks.org/?node_id=607561) for more info:

```
If you upgrade to a recent development version of CPAN (anything later than 1.88_55), it supports installing from local directories using a new "dot" syntax for distributions. Give it a dot or end a directory path with a dot and it will use that directory as if it were a downloaded and unwrapped tarball.

$ cpan .

$ cpan some/directory/.

```

**Comment by miyagawa** [comment]
Right, but these git repos and cpan tarballs do not exactly contain the same files. You might get what you want, or you might not, depending on whether the repo contains the latest auto-generated files in there.

**Comment by hongyi-zhao** [comment]
But the cpan version for my case is shown as below which is older than 1.88_55 but still can do the trick:
```
$ cpan --version
Loading internal logger. Log::Log4perl recommended for better logging
/usr/bin/cpan version 1.64 calling Getopt::Std::getopts (version 1.12 [paranoid]),
running under Perl version 5.30.3.
  [Now continuing due to backward compatibility and excessive paranoia.
   See 'perldoc Getopt::Std' about $Getopt::Std::STANDARD_HELP_VERSION.]
Nothing to install!

```

**Comment by miyagawa** [comment]
i think you've been confused. cpan and cpanm are completely different tools.

**Comment by hongyi-zhao** [comment]
Here I want to have a bootstrapped manner as below even I haven't cpanm installed, i.e., let cpan bootstrapping cpanm.

**Comment by miyagawa** [comment]
I do understand the intent. 

First of all, you don't have to clone the git repo to do this, simply running `cpan Ap::cpanminus` will install cpanm for you, assuming you have CPAN.pm configured.

I would bypass CPAN.pm since cpanm can bootstrap itself, e.g.

```
curl -O https://cpan.metacpan.org/authors/id/M/MI/MIYAGAWA/App-cpanminus-1.7044.tar.gz
tar xzvf App-cpanminus-1.7044.tar.gz
cd App-cpanminus-1.7044
perl bin/cpanm App::cpanminus
```

this will pull the latest version from CPAN, using cpanm itself.

You can also run `cpan .` instead if you really like to use CPAN.pm there, but again, if you want to use CPAN.pm, `cpan App::cpanminus` would be a much simpler way to do the same thing.

**Comment by miyagawa** [comment]
At my work, we do a similar thing by downloading the perl script from https://cpanmin.us (this will show a large file), and commit to the repo as `cpanm` executable, and use it to bootstrap the CPAN dependencies. There's no need to configure CPAN.pm beforehand.

**Comment by hongyi-zhao** [comment]
> At my work, we do a similar thing by downloading the perl script from https://cpanmin.us (this will show a large file),

But you must first prepare this file.

**Comment by hongyi-zhao** [comment]
> curl -O https://www.cpan.org/authors/id/M/MI/MIYAGAWA/App-cpanminus-1.7044.tar.gz
[...]
or even cpan ./App-cpanminus-1.7044.tar.gz

Using the precise version number is a cumbersome job, IMO.

**Comment by miyagawa** [comment]
> But you must first prepare this file and publish it on the URL mentioned above.

the URL exists already and you can download it and commit to your repo or whatever and use it too bootstrap. You can use it only for bootstrapping, e.g. `./cpanm App::cpanminus` then use the installed version from there.

> Using the precise version number is a cumbersome job, IMO.

Just using it as a starting point and you can use this to pull the latest. You can commit the tarball as `cpanmninus.tar.gz` and then use `cpan ./cpanminus.tar.gz` to install it, too.

**Comment by hongyi-zhao** [comment]
> the URL exists already

 How to create it at the very beginning?

> cpan App::cpanminus will pull the latest from CPAN

Do you mean the CPAN module will be automatically synced with the git repo?

**Comment by miyagawa** [comment]
> How to create it at the very beginning?

cpanmin.us is a host that I maintain and serves the exact same `cpanm` executable that is included in the latest CPAN, so you can download it and the file can bootstrap cpanm itself.

> Do you mean the CPAN module will be automatically synced with the latest commits on GitHub repo

the latest version on CPAN is the latest stable release of cpanm from git, which is not exactly the same as the latest commits, because the lates in git might be in development, pre-release, unstable, and you're not recommended to use it.

**Comment by miyagawa** [comment]
To stop making this thread being counter-productive, I'm going to summarize and give you a concise answer for your very question.

Q. How can I install the latest cpanm from git repo?
A. Don't do it. You are not recommended to install cpanm from git, because the files in git do not necessarily represent stability, especially in the devel branch. The files might be in development, pre-released and unstable. Use the latest version on CPAN instead.

Q. How can I install the latest version of cpanm from CPAN?
A. There are multiple ways to do this. 

a) if you already have CPAN.pm configured, run `cpan App::cpanminus` and it will pull the latest release of cpanm from CPAN.

b) if you don't have CPAN.pm configured, you can either grab the existing `cpanm` script from https://cpanmin.us/ and commit the file as `cpanm-bootstrap` to your repo, and then use it to install cpanm, by running `./cpanm-bootstrap App::cpanminus` 

the URL above contains the same `cpanm` file as in the latest version of cpanm on CPAN, and has no dependencies and includes everything it needs in the single file.

**Comment by hongyi-zhao** [comment]
Thanks a lot for your systematically, detailed and patient explanations.
