### ISSUE TITLE
Consider updating `LWP::UserAgent` to a more modern version

### ISSUE THREAD

**Issue by atoomic** [miyagawa/cpanminus#673]
Consider updating `LWP::UserAgent`

I'm not sure why we are still trying to use `5.802` 
```
suggests 'LWP::UserAgent', '5.802';
````

whereas the [Changelog](https://metacpan.org/dist/libwww-perl/changes) has multiple improvements over the years to keep improving it including for 5.8

```
...
6.76      2024-01-25 18:31:25Z
    - Simplify code slightly for Perl v5.8+ (GH#455) (James Raspass)
...

6.00    2011-03-08
...
    - Perl v5.8.8 or better is now required. For older versions of perl please
        stay with libwww-perl-5.837.
...
```

Are we fine with dropping support below `5.8.8`?

link to #672

**Comment by miyagawa** [comment]
>  we are still trying to use 5.802

That's not what it means. It says it suggests to install LWP 5.802 or newer, and in CI the latest version of LWP is actually being installed. https://github.com/miyagawa/cpanminus/actions/runs/8846389462/job/24292171782#step:4:41

The issue is that I guess the latest version of LWP doesn't support 5.8 anyways.

I personally don't think I should drop support for 5.8 for cpanm specifically, so the tests need to be fixed to test with modules that still work for 5.8.

**Comment by miyagawa** [comment]
LWP does support 5.8, but one of the transit dependencies, HTML::Tagset, requires 5.10.1.

I don't think there's anything to fix on cpanm side.
